### ISSUE TITLE
Required parameter is missing when make list-dataset request to amazon ads api

### ISSUE THREAD

**Issue by d0oo0b** [aws-solutions/amazon-marketing-cloud-uploader-from-aws#278]
**Describe the bug**
Amazon-Ads-AccountId is required parameter which is missing in the request header.
This parameter is not required when uploading data to the sandbox. However, when uploading data to the official account, missing this parameter will cause an error return of the api.

**To Reproduce**
Upload the data to the official AMC instance instead of the sandbox, and the problem can be reproduced in step 3.

**Expected behavior**
{/var/task/share/tasks.py:284} DEBUG - AMC_REQUEST_HEADERS: {'Amazon-Advertising-API-ClientId': 'amzn1.application-oa2-client.xxxxxxxxxxxxxxxxx', 'Authorization': 'xxxxxxxxxxxxxxxxxx', 'Content-Type': 'application/json', 'x-amzn-service-name': 'amazon-marketing-cloud-uploader-from-aws', 'x-amzn-service-version': 'v3.0.8', 'Amazon-Advertising-API-AdvertiserId': 'ENTITYxxxxxxxxxxx', 'Amazon-Advertising-API-MarketplaceId': 'xxxxxxxxx'}

**Please complete the following information about the solution:**
- [x] Version: [v3.0.8]

```yaml
Mappings:
  Application:
    Solution:
      Id: "SO0222"
      Name: "amcufa"
      Version: "v3.0.8"
      AppRegistryApplicationName: 'amazon-marketing-cloud-uploader-from-aws'
      ApplicationType: 'AWS-Solutions'
    SourceCode:
      GlobalS3Bucket: "solutions-reference"
      TemplateKeyPrefix: "amazon-marketing-cloud-uploader-from-aws/v3.0.8"
      RegionalS3Bucket: "solutions"
      CodeKeyPrefix: "amazon-marketing-cloud-uploader-from-aws/v3.0.8"
  AnonymizedData:
    SendAnonymizedData:
      Data: Yes
```

- [x] Region: [us-east-1]
- [x] Was the solution modified from the version published on this repository?
No
- [x] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
Yes, checked.
- [x] Were there any errors in the CloudWatch Logs?
Please refer to screenshot.

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

![Image](https://github.com/user-attachments/assets/0a7cf99a-d259-4a65-92ec-d5c487b48276)

**Additional context**
